### ISSUE TITLE
create _requireNonZeroDebtChange , _requireNotInRecoveryMode,_requireNoCollWithdrawal functions

### ISSUE THREAD

**Issue by HadasaHazan** [blockchain-audit/meridian-starknet#127]
in this issue you shouled be creating a branch from the branch **Borrow-Operation**
and when you are done you shouled create a pr to this branch **Borrow-Operation** not to main

here are links:

https://github.com/blockchain-audit/liquity-contracts/blob/98bb33179685b1e7b41aebef18730c790e81644c/src/BorrowerOperations.sol#L536C14-L536C39

https://github.com/blockchain-audit/liquity-contracts/blob/98bb33179685b1e7b41aebef18730c790e81644c/src/BorrowerOperations.sol#L540C14-L540C39

https://github.com/blockchain-audit/liquity-contracts/blob/98bb33179685b1e7b41aebef18730c790e81644c/src/BorrowerOperations.sol#L544C14-L544C38

**Comment by HadasaHazan** [comment]
you need to implement this function:
  fn _requireNotInRecoveryMode() {}

**Comment by oritlu10** [comment]
I implemented it 2 minutes ago.
