### ISSUE TITLE
create batchLiquidateTroves function

### ISSUE THREAD

**Issue by henry-hz** [blockchain-audit/meridian-starknet#41]
in this issue you shouled be creating a branch from the branch **Trove-Manager**

You can simplify to make only one liquidation. Understand the liquidation process and write it for 1 trove only.

This `batchLiquidateTroves` function is a key part of the Liquity protocol, responsible for liquidating multiple troves (collateralized debt positions) in a single transaction. Here's a breakdown of its functionality:

1. Input Validation:
   - It first checks that the input array of trove addresses is not empty.

2. Initialization:
   - Caches references to key contracts (ActivePool, DefaultPool, StabilityPool).
   - Declares local variables and a structure to store liquidation totals.

3. Price Fetch and Recovery Mode Check:
   - Fetches the current price of the collateral.
   - Checks the total LUSD (stablecoin) in the Stability Pool.
   - Determines if the system is in Recovery Mode based on the current price.

4. Liquidation Process:
   - Depending on whether the system is in Recovery Mode or Normal Mode, it calls different functions to process the liquidations:
     - `getTotalFromBatchLiquidateRecoveryMode` or
     - `getTotalsFromBatchLiquidateNormalMode`
   - These functions return the totals of debt and collateral involved in the liquidations.

5. Validation:
   - Ensures that there is actually debt to liquidate.

6. Redistribution and Offset:
   - Moves liquidated ETH and LUSD to appropriate pools.
   - Offsets debt in the Stability Pool.
   - Redistributes remaining debt and collateral.

7. Collateral Surplus Handling:
   - If there's any collateral surplus, it's sent to the CollSurplusPool.

8. System Updates:
   - Updates system snapshots, excluding the collateral used for gas compensation.

9. Event Emission:
   - Emits a Liquidation event with details of the liquidated debt and collateral.

10. Gas Compensation:
    - Sends gas compensation to the caller of this function.

This function is crucial for maintaining the health of the Liquity system by allowing efficient liquidation of multiple under-collateralized troves. It handles both normal operations and recovery mode scenarios, ensuring that the system remains solvent and stable under various market conditions.

The use of batch operations allows for more gas-efficient liquidations, which is particularly important in Ethereum-based systems where gas costs can be significant.

**Comment by GiliSasportas** [comment]
@henry-hz 
we implement this function .We have to more time to understand the logic function 
and we have a problem to rout the other file to our contract .
