### ISSUE TITLE
I need help with scarb build and  snfoundryup

### ISSUE THREAD

**Issue by oritlu10** [blockchain-audit/meridian-starknet#44]
I try to install  scarb build and  snfoundryup but i got command not found
```bash
orit@DESKTOP-QM3UF42:/mnt/c/Users/user1/meridian-starknet$ cairo-run --single-file src/LiquityMath.cairo
cairo-run: command not found
orit@DESKTOP-QM3UF42:/mnt/c/Users/user1/meridian-starknet$ snfoundryup
snfoundryup: command not found
orit@DESKTOP-QM3UF42:/mnt/c/Users/user1/meridian-starknet$ scarb build
scarb: command not found
```

**Comment by Chana-C** [comment]
To install:
curl -sL https://raw.githubusercontent.com/lambdaclass/cairo-by-example/main/build/installer.sh | bash -s 2.2.0

**Comment by Chana-C** [comment]
Install a Netfree diagnostic certificate:
https://netfree.link/wiki/%D7%94%D7%AA%D7%A7%D7%A0%D7%AA_%D7%AA%D7%A2%D7%95%D7%93%D7%94_%D7%91%D7%9E%D7%A2%D7%A8%D7%9B%D7%AA_%D7%94%D7%94%D7%A4%D7%A2%D7%9C%D7%94_%D7%9C%D7%99%D7%A0%D7%95%D7%A7%D7%A1

**Comment by oritlu10** [comment]
I found the problem in netfree
```bash
https://netfree.link/wiki/%D7%94%D7%AA%D7%A7%D7%A0%D7%AA_%D7%AA%D7%A2%D7%95%D7%93%D7%94_%D7%91%D7%9E%D7%A2%D7%A8%D7%9B%D7%AA_%D7%94%D7%94%D7%A4%D7%A2%D7%9C%D7%94_%D7%9C%D7%99%D7%A0%D7%95%D7%A7%D7%A1
```

**Comment by henry-hz** [comment]
@oritlu10 , could you fix ? if yes, pls close this issue
