### ISSUE TITLE
Implement Gas Pool

### ISSUE THREAD

**Issue by sariKahan** [blockchain-audit/meridian-starknet#70]
implement gas pool contract from:

https://github.com/blockchain-audit/liquity-contracts/blob/master/src/GasPool.sol

to:

https://github.com/blockchain-audit/meridian-starknet/blob/main/src/pool/gas_pool.cairo

**Comment by henry-hz** [comment]
We don't need the gas pool for this version, once cairo gas is much cheaper, and we leave optimizations to the end
