### ISSUE TITLE
help using an import to an interface

### ISSUE THREAD

**Issue by RacheliKm** [blockchain-audit/meridian-starknet#89]
Tring to import the IERC20 from openzepplin to use in an interface
runing the scarb build command succesfully but running the cairo run command for certain page is given error on the import

https://github.com/blockchain-audit/meridian-starknet/blob/58-add-ilusdtoken-interface/src/interfaces/ILUSDToken.cairo

**Comment by henry-hz** [comment]
use `scarb test` or `scarb build`.
