### ISSUE TITLE
help with import interface and return it in the function

### ISSUE THREAD

**Issue by RacheliPaley** [blockchain-audit/meridian-starknet#92]
import "./ILiquityBase.sol";
import "./**IStabilityPool**.sol";
import "./ILUSDToken.sol";
import "./ILQTYToken.sol";
import "./ILQTYStaking.sol";

   function stabilityPool() external view returns (**IStabilityPool**);

I need help how to do it in cairo
thanks

**Comment by henry-hz** [comment]
i need:
## what happend
## what is expected
## how to reproduce 
 - give code, commands, etc...
